import * as core from '@actions/core';
import * as github from '@actions/github';
import { Configuration, OpenAIApi } from 'openai';

async function run(): Promise<void> {
  try {
    // Get inputs
    const githubToken = core.getInput('github-token', { required: true });
    const openaiApiKey = core.getInput('openai-api-key', { required: true });

    // Initialize GitHub client
    const octokit = github.getOctokit(githubToken);
    const context = github.context;

    // Get PR details
    const prNumber = context.payload.pull_request?.number;
    if (!prNumber) {
      throw new Error('No pull request number found');
    }

    // Fetch PR content
    const { data: pullRequest } = await octokit.rest.pulls.get({
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: prNumber,
    });

    // Fetch PR diff
    const { data: prFiles } = await octokit.rest.pulls.listFiles({
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: prNumber,
    });

    // Prepare content for analysis
    const changes = prFiles.map(file => ({
      filename: file.filename,
      changes: file.patch || 'No visible changes'
    }));

    const contentToAnalyze = {
      title: pullRequest.title,
      description: pullRequest.body || 'No description provided',
      changes: changes
    };

    // Initialize OpenAI
    const configuration = new Configuration({
      apiKey: openaiApiKey,
    });
    const openai = new OpenAIApi(configuration);

    // Query OpenAI
    const completion = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content: `You are an expert at detecting AI-generated content. Analyze the following pull request and determine if it was likely generated by AI. 
          Provide your analysis in the following format:
          - Confidence Score: (0-100%)
          - Reasoning: (explain your analysis)
          - Key Indicators: (list specific elements that suggest AI or human authorship)`
        },
        {
          role: "user",
          content: JSON.stringify(contentToAnalyze, null, 2)
        }
      ],
    });

    const aiResponse = completion.data.choices[0]?.message?.content || 'No response';

    // Add comment to PR
    await octokit.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: prNumber,
      body: `## AI Detection Analysis 🔍\n\n${aiResponse}`,
    });

    // Set output
    core.setOutput('analysis', aiResponse);

  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    }
  }
}

run(); 