import * as core from '@actions/core';
import * as github from '@actions/github';
import { Configuration, OpenAIApi } from 'openai';


async function run(): Promise<void> {
  try {
    // Get inputs
    const githubToken = core.getInput('token', { required: true });
    const openaiApiKey = core.getInput('openai-api-key', { required: true });

    // Initialize GitHub client
    const octokit = github.getOctokit(githubToken);
    const context = github.context;

    // Get PR details
    const prNumber = context.payload.pull_request?.number;
    if (!prNumber) {
      throw new Error('No pull request number found');
    }

    // Fetch PR content
    const { data: pullRequest } = await octokit.rest.pulls.get({
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: prNumber,
    });

    // Fetch PR files and extract only additions
    const { data: prFiles } = await octokit.rest.pulls.listFiles({
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: prNumber,
    });

    // Process each file to extract only additions
    const changes = prFiles.map(file => {
      // Split the patch into lines
      const patch = file.patch || '';
      const lines = patch.split('\n');
      
      // Only keep lines that start with '+' (additions) and remove the '+' prefix
      const additions = lines
        .filter(line => line.startsWith('+'))
        .map(line => line.substring(1))
        .join('\n');

      return {
        filename: file.filename,
        additions: additions || 'No additions'
      };
    });

    const contentToAnalyze = {
      title: pullRequest.title,
      description: pullRequest.body || 'No description provided',
      changes: changes
    };

    // Use the new function instead of inline OpenAI call
    const aiResponse = await analyzeWithGPT(openaiApiKey, contentToAnalyze);
    
    // Extract confidence score
    const confidenceScore = await extractConfidenceScore(aiResponse);
    
    // Create the comment body
    const commentBody = `## AI Detection Analysis 🔍\n\n${aiResponse}\n\n${
      confidenceScore > 80 
        ? '⚠️ **Warning:** High confidence that this PR was generated by AI'
        : '✅ No strong indicators of AI generation detected'
    }`;

    // Add comment to PR
    await octokit.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: prNumber,
      body: commentBody,
    });

    // Set outputs
    core.setOutput('analysis', aiResponse);
    core.setOutput('confidence_score', confidenceScore);

    // Fail if confidence score is too high
    if (confidenceScore > 80) {
      if (core.getInput('fail-when-confident')) {
        core.setFailed(`AI detection confidence score (${confidenceScore}%) exceeds threshold of 80%`);
      }

      const prLabel = core.getInput('pr-label');
      if (prLabel) {
        core.info(`Adding label "${prLabel}" to PR #${prNumber}`);
        await octokit.rest.issues.addLabels({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: prNumber,
          labels: [prLabel],
        });
      }
    }

  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    }
  }
}

// Export these functions for testing
export async function extractConfidenceScore(response: string): Promise<number> {
  try {
    // Look for patterns like "Confidence Score: 85%" or "Confidence Score: 85"
    const match = response.match(/Confidence Score:\s*(\d+)%?/i);
    if (match && match[1]) {
      return parseInt(match[1], 10);
    }
    return 0;
  } catch (error) {
    core.warning('Failed to parse confidence score');
    return 0;
  }
}

export async function analyzeWithGPT(openaiApiKey: string, content: any): Promise<string> {
  // Initialize OpenAI
  const configuration = new Configuration({
    apiKey: openaiApiKey,
  });
  const openai = new OpenAIApi(configuration);

  // Query OpenAI with a structured prompt
  const completion = await openai.createChatCompletion({
    // model: "gpt-3.5-turbo",
    model: "chatgpt-4o-latest",
    messages: [
      {
        role: "system",
        content: `You are an expert at detecting AI-generated content. Your task is to analyze pull requests and determine if they were likely generated by AI.
        
        Important: You must start your response with a confidence score line in exactly this format:
        Confidence Score: X%
        where X is a number between 0 and 100.
        
        Then provide your analysis in this format:
        Reasoning: (explain your analysis)
        Key Indicators: (list specific elements that suggest AI or human authorship)
        
        A high confidence score (>80%) means you are very confident the content was AI-generated.
        A low confidence score (<20%) means you are very confident the content was human-generated.
        Use scores between 20-80% when there is uncertainty.`
      },
      {
        role: "user",
        content: JSON.stringify(content, null, 2)
      }
    ],
  });

  return completion.data.choices[0]?.message?.content || 'No response';
}

run();

